Medium/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls"), name="blog-urls"),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

blog/urls.py
from . import views
from django.urls import path

urlpatterns = [

    path("", views.landing_page, name='landing_page'),
    path('about/', views.about, name='about'),
    path('write/', views.write, name='write'),
    path('profile/', views.profile, name='profile'),
    path("PostList", views.PostList.as_view(), name="read"),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


STATUS = ((0, "Draft"), (1, "Published"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='blogpost_like', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

blog/forms.py
from .models import Comment
from django import forms

# to publish blog posts from front end
from .models import Post
from django_summernote.widgets import SummernoteWidget


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


# for users to publish posts from the write post page
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'featured_image', 'excerpt', 'content']
        exclude = ['author', 'status', 'likes', 'slug']
        widgets = {
            'content': SummernoteWidget(),  # Use SummernoteWidget for the content field
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Post
from .forms import CommentForm


from django.shortcuts import render, redirect
from django.utils.text import slugify
from .forms import PostForm
from .models import STATUS
from django.contrib.auth.decorators import login_required


class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "index.html"
    paginate_by = 6


class PostDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )
    
    def post(self, request, slug, *args, **kwargs):

        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "comment_form": comment_form,
                "liked": liked
            },
        )


class PostLike(View):
    
    def post(self, request, slug, *args, **kwargs):
        post = get_object_or_404(Post, slug=slug)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('post_detail', args=[slug]))
    


def about(request):
    return render(request, 'about.html')


def landing_page(request):
    # Retrieve the six most recent posts
    recent_posts = Post.objects.filter(status=1).order_by('-created_on')[:6]
    return render(request, 'landing_page.html', {'recent_posts': recent_posts})


@login_required
def profile(request):
    user = request.user
    posts = Post.objects.filter(author=user)
    return render(request, 'profile.html', {'posts': posts, 'user': user})


@login_required
def write(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user

            # Set status to "published"
            post.status = STATUS[1][0]
            
            # Generate unique slug based on the title
            slug = slugify(post.title)
            unique_slug = slug
            counter = 1
            while Post.objects.filter(slug=unique_slug).exists():
                unique_slug = f'{slug}-{counter}'
                counter += 1
            post.slug = unique_slug
            
            post.save()
            return redirect('post_detail', slug=post.slug)  # Redirect to post_detail view after successful submission
    else:
        form = PostForm()
    return render(request, 'write.html', {'form': form})

templates/about.html
{% extends "base.html" %}

{% block content %}


<div class="full-width-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="lead">Everyone has a <br> story to tell.</h1>
                <p class="lead-1"> Medium is a home for human stories and ideas. Here, anyone can share insightful
                    perspectives, useful
                    knowledge, and life wisdom with the world—without building a mailing list or a following first. The
                    internet is noisy and chaotic; Medium is quiet yet full of insight. It’s simple, beautiful,
                    collaborative, and helps you find the right audience for whatever you have to say.</p>
                <p class="lead-1">We believe that what you read and write matters. Words can divide or empower us,
                    inspire or discourage
                    us. In a world where the most sensational and surface-level stories often win, we’re building a
                    system
                    that rewards depth, nuance, and time well spent. A space for thoughtful conversation more than
                    drive-by
                    takes, and substance over packaging.</p>
                <p class="lead-2">
                <div class="highlighted-text">
                    Ultimately, our goal is to deepen our collective understanding of the world through the power of
                    writing.
                </div>
                </p>
                <p class="lead-1">Over 100 million people connect and share their wisdom on Medium every month. Many are
                    professional
                    writers, but just as many aren’t — they’re CEOs, computer scientists, U.S. presidents, amateur
                    novelists, and anyone burning with a story they need to get out into the world. They write about
                    what
                    they’re working on, what’s keeping them up at night, what they’ve lived through, and what they’ve
                    learned that the rest of us might want to know too.</p>
                <p class="lead-1">Instead of selling ads or selling your data, we’re supported by a growing community of
                    Medium members who
                    align with our mission. If you’re new here, start exploring. Dive deeper into whatever matters to
                    you.
                    Find a post that helps you learn something new, or reconsider something familiar—and then share your
                    own
                    story.</p>
            </div>
        </div>
    </div>
</div>

<div class="divider">
</div>


<a href="{% url 'read' %}" class="strip">
    Start reading
    <i class="fa-solid fa-arrow-right"></i>
</a>

<div class="divider">
</div>

<a href="{% url 'write' %}" class="strip">
    Start writing
    <i class="fa-solid fa-arrow-right"></i>
</a>


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Medium</title>

    <!--FavIcon-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_io/favicon-16x16.png' %}">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/90a4223dfb.js" crossorigin="anonymous"></script>

    <!-- JS -->
<script src="{% static 'js/script.js' %}"></script>



</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white py-3 sticky-top">
        <div class="container-fluid">
            
                        <a class="navbar-brand ms-5" href="{% url 'landing_page' %}"><img src="https://res.cloudinary.com/dugcwv1mf/image/upload/v1710239682/Project%201/1679302694Medium-Logo-PNG_m5tjaz.png"
                            alt="Logo" class="logo-image" style="width: 140px"></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
                    <li class="nav-item mx-2">
                        <a class="nav-link active" aria-current="page" href="{% url 'landing_page' %}">Home</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link active" aria-current="page" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link active" aria-current="page" href="{% url 'read' %}">Read</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item mx-2">
                        <a class="nav-link active" href="{% url 'write' %}">Write</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link active" href="{% url 'profile' %}">Profile</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link active" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item mx-2">
                        <a class="nav-link active" href="{% url 'account_login' %}">Sign in</a>
                    </li>
                    <li class="nav-item mx-4">
                        <a class="nav-link btn btn-dark btn-sm rounded-pill text-white px-4" href="{% url 'account_signup' %}">Get Started</a>
                    </li>    
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main class="flex-shrink-0 main-bg">

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <a class="footer" href="{% url 'landing_page' %}">
        <img src="https://res.cloudinary.com/dugcwv1mf/image/upload/v1710239682/Project%201/1679302694Medium-Logo-PNG_m5tjaz.png"
            alt="Logo" class="logo-image" style="width: 140px; margin-left: 20px;">
        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item px-2"><a href="{% url 'about' %}" class="nav-link px-2 text-dark">About</a></li>
            <li class="nav-item px-2"><a href="https://www.termsfeed.com/live/1f8a0436-3133-4a5e-bdd6-c20dc0330b09" class="nav-link px-2 text-dark" target="_blank"
                rel="Medium Terms Policy">Terms</a></li>
            <li class="nav-item px-2"><a href="https://www.termsfeed.com/live/0f0be1b6-2436-4b8a-a785-82e80f8b71c3" class="nav-link px-2 text-dark" target="_blank"
                rel="Medium Privacy Policy">Privacy</a></li>
        </ul>
</footer>

    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                                {% else %}
                                <img class="card-img-top" src=" {{ post.featured_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug  %}" class="post-link">
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
                                {{ post.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/landing_page.html
{% extends "base.html" %}

{% block content %}

<!--Jumbotron-->
<div class="carousel-inner">
  <div class="carousel-item active tablet">
    <img src="https://res.cloudinary.com/dugcwv1mf/image/upload/v1710248012/Project%201/89_hd0fx2.jpg" class="d-block w-100 carousel-img" alt="Landing page image">
    <div class="container">
      <div class="carousel-caption text-start">
        <h1 class="custom-display text-dark">Stay curious.</h1>
        <p class="custom-display-2 opacity-75 text-dark">Discover stories, thinking, and expertise<br> from writers on any topic.</p>
        <p><a class="btn btn-lg btn-dark rounded-pill text-white px-5 jumbotron-btn" href="{% url 'read' %}">Start Reading</a></p>
      </div>
    </div>
  </div>
</div>

<!--Recent articles -->
<div class="container mt-4">
  <h2 class="mb-4"><i class="fa-solid fa-chart-line"></i> Trending on Medium</h2>
  <div class="row">
    {% for post in recent_posts %}
    <div class="col-md-4 mb-4">
      <div class="card">

        <div class="card-img-container">

        {% if "placeholder" in post.featured_image.url %}
          <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" class="card-img-top" alt="{{ post.title }}">
        {% else %}
          <img src="{{ post.featured_image.url }}" class="card-img-top" alt="{{ post.title }}">
        {% endif %}

      </div>

        <div class="card-body">
          <h5 class="card-title">{{ post.title }}</h5>
          <p class="card-text">{{ post.excerpt }}</p>
          <a href="{% url 'post_detail' slug=post.slug %}" class="btn btn-black btn-pill">Read more</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!--Get started Block -->
<div class="bottom">
  <div class="wisdom">
  <p class="strip-landing">Unlock a World of Wisdom</p>
</div>
  <div class="text-center">
    <p><a class="btn btn-lg btn-dark rounded-pill px-5 btn-custom-1" href="{% url 'read' %}">Get Started</a>
    </p>
  </div>
</div>


{% endblock %}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}
{% load crispy_forms_tags %}

<!-- Masthead -->
<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-12 masthead-text">

                <div class="masthead-content">

                <h1 class="post-title">{{ post.title }}</h1>
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>

            </div>

            </div>
        </div>
    </div>
</div>

<!-- Featured image -->
<div class="container">
    <div class="row g-0">
        <div class="col-md-12">
            {% if "placeholder" in post.featured_image.url %}
            <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" class="featured-image" alt="Featured Image">
            {% else %}
            <img src="{{ post.featured_image.url }}" class="featured-image" alt="Featured Image">
            {% endif %}
        </div>
    </div>
</div>

<!--Post content-->
<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ post.content | safe }}
                </p>
                <div class="row">

                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'post_like' post.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        <!-- The number of likes goes before the closing strong tag -->
                        <span class="text-secondary">{{ post.number_of_likes }} </span>
                        </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-8 card mb-4 mt-3">
            <div class="card-body">
                <h3>Leave a comment:</h3>
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="col-md-8 card mb-4 mt-3">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.name }}
                        <span class="text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
    </div>

</div>

{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1 class="text-center pt-5 pb-5">Welcome to your profile, {{ user.username }}!</h1>

    {% if posts %}
        <h2 class="text-center pb-3">Your Published Posts:</h2>
        <div class="list-group text-center">
            {% for post in posts %}
                <a href="{% url 'post_detail' post.slug %}" class="list-group-item list-group-item-action post-link">
                    {{ post.title }}
                </a>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-center pb-3">You haven't published any posts yet.</p>
        <div class="text-center">
        <p><a class="btn btn-lg btn-dark rounded-pill text-white px-5 btn-custom" href="{% url 'write' %}">Create Post</a></p>
    </div>
    {% endif %}
</div>

{% endblock %}

templates/write.html
{% extends "base.html" %}

{% block content %}



<div class="container">
    <h1 class="text-center mt-5">Create a New Blog Post</h1>

    <form method="post" enctype="multipart/form-data" class="mt-4">
        {% csrf_token %}

        <div class="row justify-content-center">
            <div class="col-md-6">
                <!-- Title field -->
                <div class="mb-3">
                    <label for="id_title" class="form-label">Title</label>
                    <input type="text" class="form-control" id="id_title" name="title">
                </div>

                <!-- Featured Image field -->
                <div class="mb-3">
                    <label for="id_featured_image" class="form-label">Featured Image</label>
                    <input type="file" class="form-control" id="id_featured_image" name="featured_image">
                </div>

                <!-- Excerpt field -->
                <div class="mb-3">
                    <label for="id_excerpt" class="form-label">Excerpt</label>
                    <textarea class="form-control" id="id_excerpt" name="excerpt"></textarea>
                </div>

                <!-- Content field -->
                <div class="mb-3">
                    <label for="id_content" class="form-label">Content</label>
                    {{ form.content }}
                </div>

                <!-- Publish button -->
                    <button type="submit" class="btn btn-dark btn-lg w-100">Publish</button>
            </div>
        </div>
    </form>
</div>


{% endblock %}